In [13]:
import h5py
import numpy as np

with h5py.File('./data/Chair-1/train-00.h5', 'r') as f:
    print("Keys:", list(f.keys()))
    points = f['pts'][:]
    print("Points shape:", points.shape)
    print(f['gt_label'][:])
    print(f['gt_label'][:].shape)
    print( np.unique(f['gt_label'][:]))

Keys: ['gt_label', 'gt_mask', 'gt_other_mask', 'gt_valid', 'pts']
Points shape: (1024, 10000, 3)
[[4 2 4 ... 5 4 2]
 [5 2 4 ... 5 2 5]
 [5 2 4 ... 5 2 5]
 ...
 [5 2 4 ... 5 4 2]
 [2 4 4 ... 5 2 4]
 [2 4 3 ... 5 2 5]]
(1024, 10000)
[0 1 2 3 4 5]


[0 1 2 3 4 5]

Chair-level-1.txt
2 chair/chair_head subcomponents
5 chair/chair_back subcomponents
16 chair/chair_arm subcomponents
23 chair/chair_base subtypes
45 chair/chair_seat subcomponents

0可能是 背景类（unlabeled / other），用于标记不属于已知 part 的点

In [14]:
with h5py.File('./data/Bag-1/train-00.h5', 'r') as f:
    print("Keys:", list(f.keys()))
    points = f['pts'][:]
    print("Points shape:", points.shape)
    print(f['gt_label'][:])
    print(f['gt_label'][:].shape)
    print( np.unique(f['gt_label'][:]))

Keys: ['gt_label', 'gt_mask', 'gt_other_mask', 'gt_valid', 'pts']
Points shape: (92, 10000, 3)
[[1 3 3 ... 1 1 1]
 [1 1 2 ... 1 1 1]
 [1 1 2 ... 1 1 1]
 ...
 [2 1 1 ... 1 1 1]
 [2 1 1 ... 1 1 1]
 [2 1 2 ... 1 1 1]]
(92, 10000)
[0 1 2 3]


Bag-level-1.txt

2 bag/bag_body leaf
3 bag/handle leaf
4 bag/shoulder_strap leaf